version: '3'

name: landmarks

services:
  web:
    build: .
    ports:
      - 8084:8082
    networks:
      - landmarks
    environment:
      NEO4J_PASSWORD: $NEO4J_PASSWORD
      NEO4J_CONNECTION_URI: $NEO4J_CONNECTION_URI
      JENNY_PASSWORD: $JENNY_PASSWORD
      DERRICK_PASSWORD: $DERRICK_PASSWORD

networks:
  landmarks:
