# fly.toml app configuration file generated for landmarks on 2023-06-28T21:28:39-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "landmarks"
primary_region = "sea"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
