version: '3'

name: landmarks

services:
  web:
    build:
      dockerfile: server.Dockerfile
    ports:
      - 8084:8080
    networks:
      - landmarks
    environment:
      NEO4J_PASSWORD: $NEO4J_PASSWORD
      NEO4J_CONNECTION_URI: $NEO4J_CONNECTION_URI
      JENNY_PASSWORD: $JENNY_PASSWORD
      DERRICK_PASSWORD: $DERRICK_PASSWORD
      ADMIN_TOKEN: $ADMIN_TOKEN
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION: $AWS_REGION

networks:
  landmarks:
